// ======================================
// FILE: src/constants/error.codes.ts
// ======================================

/**
 * Error Codes (Stable)
 * -----------------------------------
 * These codes NEVER change once released.
 * Frontend can rely on them for UI handling.
 */
export enum ErrorCode {
  // Common
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  INVALID_REQUEST = "INVALID_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",

  // Required fields
  EMAIL_REQUIRED = "EMAIL_REQUIRED",
  PASSWORD_REQUIRED = "PASSWORD_REQUIRED",
  USERNAME_REQUIRED = "USERNAME_REQUIRED",
  PHONE_REQUIRED = "PHONE_REQUIRED",
  DIAL_CODE_REQUIRED = "DIAL_CODE_REQUIRED",
  OTP_REQUIRED = "OTP_REQUIRED",
  SESSION_TOKEN_REQUIRED = "SESSION_TOKEN_REQUIRED",
  ACCESS_TOKEN_REQUIRED = "ACCESS_TOKEN_REQUIRED",
  REFRESH_TOKEN_REQUIRED = "REFRESH_TOKEN_REQUIRED",
  IDENTIFIER_REQUIRED = "IDENTIFIER_REQUIRED",

  // Validation
  INVALID_EMAIL = "INVALID_EMAIL",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  INVALID_USERNAME = "INVALID_USERNAME",
  INVALID_PHONE_NUMBER = "INVALID_PHONE_NUMBER",
  INVALID_DIAL_CODE = "INVALID_DIAL_CODE",
  INVALID_OTP = "INVALID_OTP",
  PASSWORDS_DO_NOT_MATCH = "PASSWORDS_DO_NOT_MATCH",

  // Auth
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",

  // Session / OTP
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  SESSION_INVALID = "SESSION_INVALID",
  OTP_EXPIRED = "OTP_EXPIRED",
  OTP_ATTEMPTS_EXCEEDED = "OTP_ATTEMPTS_EXCEEDED",
  OTP_RESEND_LIMIT_REACHED = "OTP_RESEND_LIMIT_REACHED",
}
